### ISSUE TITLE
Feature Request: Uptime and wifi_rssi other debug data as entity

### ISSUE THREAD

**Issue by DB1BMN-collection** [lumapu/ahoy#1481]
Hi,
since we are still observing sporadic restarts I thought it would be a good idea to have the Uptime and other data as entity which could easilier be implemented in Home Assistant etc.

A collegue recommended me the program MQTT Explorer [1] which shows that already uptime, wifi_rssi and heap info are already sent via MQTT. That's fine!
![grafik](https://github.com/lumapu/ahoy/assets/118214924/11a7c326-be21-485c-8908-56f12c2e7559)

Never the less Home Assistant by default can not display theese data, as they are not defined as an entity I guess.

I was fiddeling yesterday night in the configuration.yaml (which I am a completely noob at) and ended up with an diagram showing Uptime vs. RSSI.
![grafik](https://github.com/lumapu/ahoy/assets/118214924/6e09c064-51a7-4ef3-a054-43f0ada7ffdf)

Just paste the following code into the configuration.yaml:
```yaml
mqtt:
    #AhoyDTU
    sensor:
        - name: "AHOY Uptime"
            unique_id: "ahoy_uptime"
            state_topic: inverter/uptime
            unit_of_measurement: "s"
            icon: "mdi:clock"

        - name: "AHOY RSSI"
            unique_id: "ahoy_rssi"
            state_topic: inverter/wifi_rssi
            unit_of_measurement: "dBm"
            icon: "mdi:wifi"
```

Take care of the indents and don't forget the dashes ("-") before the "name"-tags!

I think it would be much easier for debugging if anybody could track uptime, rssi and heap-info when they are available as entities and it would help cathc rare restart events.

What do you think?

[1] http://mqtt-explorer.com/

P.S. It seems the "code"-tag seems not to work correctly, WTF!?
