### ISSUE TITLE
MQTT -> Mosquitto -> Telegraf -> InfluxDB

### ISSUE THREAD

**Issue by Waldo56** [lumapu/ahoy#517]
Hi, habe Probleme mit der Konfiguration von Telegraf betreffend JSON Objekte der Ahoy. Ich würde ja gerne das Plugin im Telegraf Consumer erstellen. Mir fehlt aber die Basis wie die JSON Strukturen am Input von Telegraf aussehen. Ich sehe zwar Strukturen im MQTTFx, weiss aber nicht wirklich ob diese passen. Hat jemand schon mal das telegraf.conf File entsprechend konfiguriert? Wäre für Hinweise, Tipps, oder gar einen Auszug aus einem telegraf.conf File dankbar.

**Comment by c1328** [comment]
Hi! Schau dir mal [https://grafana.com/grafana/dashboards/16850-pv-power-ahoy/](url) an. Da findest du auch etwas zur MQTT/Telegraf/Influx Konfiguration. Bei Fragen gern melden :-)

**Comment by Waldo56** [comment]
Danke Dir.

**Comment by gone-for-coding** [comment]
Ich habe es wie folgt erfolgreich laufen:
```toml
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["ahoyTopic/#"]
  qos = 0
  connection_timeout = "60s"
  username = "xxx"
  password = "xxx"
  data_format = "value"
  data_type = "float"
  ## Route to pv1 bucket
  [inputs.mqtt_consumer.tags]
	target_bucket = "pv1"
```
