### ISSUE TITLE
Feature Request: add timeout for MQTT / Home Assistant Entries to become Unavailable

### ISSUE THREAD

**Issue by juvi007** [lumapu/ahoy#943]
### Platform

ESP8266

### Assembly

I did the assebly by myself

### nRF24L01+ Module

nRF24L01+ plus

### Antenna

external antenna

### Power Stabilization

nothing

### Connection picture

- [ ] I will attach/upload an Image of my wiring

### Version

0.6.9

### Github Hash

15ec6a0

### Build & Flash Method

AhoyDTU Webinstaller

### Setup

MQTT with 0s Inervall

### Error description

when Inverse stops receiving Data ist sets the Home Assistant Entries to Unavailable wich is displayed in my Dashboard but I think it should display 0.
![image](https://github.com/lumapu/ahoy/assets/99984229/18293da6-2001-4e38-958f-c10356bab3f7)

**Comment by rmayergfx** [comment]
@juvi007 
This is totally normal with this MQTT Settings. you can change this by adding the sensort in a mqtt.yaml and then include this in your configuration.yaml. Then the values will stay at the last received and not change to unavailable until the System is online again.

Take a look here how to do:
https://github.com/lumapu/ahoy/issues/938#issuecomment-1546666101

**Comment by ottelo9** [comment]
@rmayergfx 
Doesnt work for me. I tried it with this config:

mqtt.yaml

```
sensor:
  - name: "Leistung Schuppen (800W)"
    unique_id: hm800_schuppen_p_ac
    state_topic: "inverter/HM800-Schuppen/ch0/P_AC"
  - name: "Leistung Carport (800W)"
    unique_id: hm800_carport_p_ac
    state_topic: "inverter/HM800-Carport/ch0/P_AC"
```


<img width="205" alt="2023_06_20_14_00_18_History_Home_Assistant" src="https://github.com/lumapu/ahoy/assets/33122175/eb67e615-f6b3-420b-ba0a-12f0d18dbc4b">
